# Generated by Django 4.1.3 on 2023-01-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Gua_name',
            new_name='Guardian_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Gua_number',
            new_name='Guardian_number',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Gua_occupation',
            new_name='Guardian_occupation',
        ),
    ]
