# Generated by Django 4.1.3 on 2023-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(default='drisya1234', max_length=20)),
                ('Password2', models.CharField(max_length=20)),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Transgender')], max_length=20)),
                ('Mobile_number', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('District', models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Kottayam', 'Kottayam'), ('Ernakulam', 'Ernakukulam'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode')], max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Branch', models.CharField(choices=[('Aluva', 'Aluva'), ('Edapally', 'Edapally'), ('Vazhakala', 'Vazhakala'), ('Kakkanad', 'Kakkanad'), ('Mattancheri', 'Mattancheri')], max_length=30)),
                ('Account_type', models.CharField(choices=[('Savings account', 'Savings account'), ('Current account', 'Current account'), ('Salary account', 'Salary account'), ('Fixed deposit account', 'Fixed deposit account'), ('Recurring deposit account', 'Recurring deposit account'), ('NRI account', 'NRI account')], max_length=50)),
                ('Meterials_provide', models.CharField(choices=[('Credit card', 'Credit card'), ('Debit card', 'Debit card'), ('Pass book', 'Pass book'), ('Cheque book', 'Cheque book')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Client details',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
