# Generated by Django 4.1.3 on 2023-03-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Password2',
            new_name='Confirm_password',
        ),
    ]
