# Generated by Django 4.1.3 on 2023-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_password2_client_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Account_type',
            field=models.CharField(choices=[('Savings account', 'Savings account'), ('Current account', 'Current account'), ('Salary account', 'Salary account'), ('Fixed deposit account', 'Fixed deposit account'), ('Recurring deposit account', 'Recurring deposit account'), ('NRI account', 'NRI account')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Branch',
            field=models.CharField(choices=[('Aluva', 'Aluva'), ('Edapally', 'Edapally'), ('Vazhakala', 'Vazhakala'), ('Kakkanad', 'Kakkanad'), ('Mattancheri', 'Mattancheri')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Confirm_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='District',
            field=models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Kottayam', 'Kottayam'), ('Ernakulam', 'Ernakukulam'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Transgender')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Meterials_provide',
            field=models.CharField(choices=[('Credit card', 'Credit card'), ('Debit card', 'Debit card'), ('Pass book', 'Pass book'), ('Cheque book', 'Cheque book')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Password',
            field=models.CharField(default='drisya1234', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
