# Generated by Django 4.1.3 on 2023-03-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_client_account_type_alter_client_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Username',
            new_name='username',
        ),
    ]
